on:
  workflow_call:

jobs:
  labels:
    runs-on: ubuntu-latest

    steps:
      - uses: EndBug/label-sync@52074158190acb45f3077f9099fea818aa43f97a # v2.3.3
        with:
          config-file: https://raw.githubusercontent.com/zacjmurphy/jellyfin-meta-plugins/main/.github/plugin-repo-labels.yaml
          delete-other-labels: true
          token: ${{ GITHUB_TOKEN }}